[package]
name = "monkey-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"]}
lazy_static = "1.4.0"
log = "0.4.21"
whoami = "1.5.1"
